version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.17
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: "@types/faker"
    versions:
    - 5.1.5
    - 5.1.6
    - 5.1.7
    - 5.5.0
    - 5.5.1
  - dependency-name: react-native-screens
    versions:
    - 2.17.1
    - 2.18.0
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: "@react-navigation/bottom-tabs"
    versions:
    - 5.11.7
    - 5.11.8
    - 5.11.9
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.46
    - 0.63.47
    - 0.63.48
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.63.52
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: react-native-reanimated
    versions:
    - 1.13.2
    - 2.0.0
    - 2.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: "@react-navigation/drawer"
    versions:
    - 5.12.3
    - 5.12.4
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.2
    - 5.9.3
  - dependency-name: "@react-navigation/stack"
    versions:
    - 5.14.2
    - 5.14.3
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.0
  - dependency-name: "@types/react-test-renderer"
    versions:
    - 17.0.0
  - dependency-name: react-native-safe-area-context
    versions:
    - 3.1.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@react-native-community/masked-view"
    versions:
    - 0.1.10
